### ISSUE TITLE
Add more tests before trying to unpack files from spk

### ISSUE THREAD

**Issue by mbirth** [jdel/sspks#18]
- test for required php-phar extension
- test for writeable permissions on package dir
- test for allow_url_fopen = True
- probably write a test file and delete again
- probably use PharData class instead of fopen method

**Comment by jdel** [comment]
It would be great to have a status page that shows the status of all prerequisites and gives the user a hint on how to remediate.

What I have in mind is the Kibana status page.

https://www.elastic.co/guide/en/kibana/4.5/images/kibana-status-page.png

We don't really need the top metrics though.
