### ISSUE TITLE
Separate extracted meta files and package directory

### ISSUE THREAD

**Issue by mbirth** [jdel/sspks#33]
Currently, all meta files extracted from packages (`INFO`, icons, thumbnails/screenshots) are going to the same directory where the packages reside.

It's probably better to have those extracted/redundant files in a separate directory, e.g. `cache`. So if problems arise, one can just delete all files in that `cache` directory and they're going to get extracted from the Synology packages again on the next run.

This also makes the `packages` directory more tidy / gives a better overview over packages on offer.

(This probably also means there should be some cleanup when there are files in `cache` for a package no longer existing in `packages`. Or we leave that to the user, to occasionally tidy up everything.)

**Comment by jdel** [comment]
👍 totally agreed ! User is responsible for cleaning the cache once in a while, or setup a cronjob.
