### ISSUE TITLE
Support generic architecture tags, e.g. "x86_64"

### ISSUE THREAD

**Issue by mbirth** [jdel/sspks#36]
I noticed that e.g. official Synology packages only specify:

```
arch="x86_64"
```

instead of listing compatible architectures (e.g. `avoton` or `grantley` are both `x86_64`).

We should add a mapping to accommodate this. [SynoCommunity](https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model) lists a few.

**Comment by benrubson** [comment]
Here are the available platforms, from the [official building tool](https://github.com/SynologyOpenSource/pkgscripts-ng) :
```
# ./pkgscripts-ng/EnvDeploy -v 6.0 -l
Available platforms: 6281 alpine alpine4k armada370 armada375 armada38x armadaxp avoton braswell bromolow cedarview comcerto2k evansport monaco qoriq x64 broadwell grantley
```

And the arch families it produces (in INFO files) :
```
arch="88f6281"
arch="alpine alpine4k"
arch="armada370"
arch="armada375"
arch="armada38x"
arch="armadaxp"
arch="comcerto2k"
arch="evansport"
arch="monaco"
arch="qoriq"
arch="x86 bromolow cedarview avoton braswell broadwell grantley"
```

**Comment by mbirth** [comment]
Just for the record: Families for `ipq806x`, `northstarplus` (both: `armv7`), `powerpc` and all the `ppc8...` ones (made them `ppc`) are educated guesses.
