### ISSUE TITLE
Question - auto install dependencies

### ISSUE THREAD

**Issue by jenskastensson** [jdel/sspks#42]
Hello, first of all, thanks for sharing your work, it works great!
Do you know if it is possible to automatically install depending packages (silently) ?
Some of the official Synology packages like phpMyAdmin-4.6.5-0170.spk does that - when it is launched from Package Center, But if the spk is downloaded and installed manually, it just shows the message regarding dependencies. So it seem to be a feature of the spk server.
Jens

**Comment by benrubson** [comment]
Hello,
You should try the `install_dep_services` OPTION field :
https://developer.synology.com/developer-guide/synology_package/INFO_optional_fields.html
By default the installation is quickly made (no wizard), so dependencies should be installed silently too.

**Comment by jdel** [comment]
Thanks for reporting this @jenskastensson, I will have a look.

**Comment by jenskastensson** [comment]
@benrubson Thx, the install_dep_services indeed does the job,  I was using install_dep_packages, but it does not cause deps to be installed. I'm not sure I understand what the difference is, but Iäll play around. Thx again, you can close this

**Comment by jdel** [comment]
Thanks Ben 🥇  😆
