### ISSUE TITLE
Question: production and test server - recommended solution?

### ISSUE THREAD

**Issue by jenskastensson** [jdel/sspks#44]
Hello, 
I need two different spk servers, one for production and one for test.  The production server runs on AWS/EC2 and to save money, it'd be nice use the same instance. 
What are my options, can I run a second spks serving on different port? Any creative ideas are welcome 
Thanks Jens

**Comment by mbirth** [comment]
Just setup a second web server on a different port and point it to a different directory than the first one.

**Comment by jdel** [comment]
Or you can use the docker image https://hub.docker.com/r/jdel/sspks/

**Comment by jenskastensson** [comment]
Thx
