### ISSUE TITLE
Packages not shown for architecture 88f6282

### ISSUE THREAD

**Issue by schumi2004** [jdel/sspks#45]
I think i have the latest version running and noticed that packages aren't shown for models with CPU architecture 88f6282 

I think they should show the same packages that are shown for architecture 88f6281.

https://www.synology.com/en-us/knowledgebase/DSM/tutorial/General/What_kind_of_CPU_does_my_NAS_have

**Comment by jdel** [comment]
Can you check which version you are running ? These 3 lines should take care of this very specific corner case: https://github.com/jdel/sspks/blob/76df7ac491e85206b294892bf902947c95dcc398/lib/SSpkS/Handler/SynologyHandler.php#L49

**Comment by mbirth** [comment]
What about having a server-side flag to create a "virtual package" which shows some debug information in the description? That could be useful to debug the communication between the Syno and SSpkS, I think.

**Comment by jdel** [comment]
@mbirth could you explain a bit more how you would implement that ? Specifically putting the server in "debug mode" then all the clients will get debug info ?

I'd be more in favor of having a GET / POST param that adds `debug` array into the output json. Then simply do a `curl` to simulate a syno connecting ?

But first, @schumi2004, could you please confirm which version you are using ? Possibly try the [docker container](https://hub.docker.com/r/jdel/sspks/) ?

**Comment by mbirth** [comment]
@jdel I'd like to have a possibility for users to be able to get what their Synology device sends to the server. I'd implement it so that a package called "SSpkS Debug" (or similar) is returned for all architectures which contains a bit of debug info in the description. This way it shouldn't make problems as the other packages are returned as well and users will only find the "virtual" package when they actively search for it.

**Comment by jdel** [comment]
Oh yeah I quite like that idea ! And let's make that package "Beta" so regular users that don't have the beta channel on don't see it. I'll make a new ticket for this feature so we don't ruin this issue :)

**Comment by schumi2004** [comment]
My apologies for not responding I totally forgot this. I will update to latest version and report back.
It can also be closed so i can re-open when needed.

**Comment by schumi2004** [comment]
Okay, updated to latest version.

root@DS715:/volume1/web/syno.whocarez.nl# git log
commit a5ad86e952e0a750d18c42292af618eeb2cf7a1f
Author: Julien Del-Piccolo <jdel@users.noreply.github.com>
Date:   Tue Aug 15 23:33:09 2017 +0200

    Add version info from env variables (#41)

    Override from ENV variables:

And no packages found for arch 88f6282.

Also checked sspks/lib/SSpkS/Handler/SynologyHandler.php as requested by @jdel and found this.

        // more parameters: timezone and unique

        if ($arch == '88f6282') {
            $arch = '88f6281';
        }

**Comment by schumi2004** [comment]
A example:

package="oscam"
version="1.20-r11385-3"
description="OSCam is a multi-protocol and cross-platform card server. A card server is a software which acts as a key host for card clients. A card server usually has one or more smartcard readers and ethernet interface. It emulates conditional access module (CAM) for accessing smartcard and offers virtual common interface to the clients. OSCam has a card client and a web interface"

arch="88f6281"
maintainer="schumi2004"
maintainer_url=""
distributor=""
distributor_url=""
firmware="5.0-4458"
report_url=""
reloadui="yes"
displayname="OSCam"
dsmuidir="app"
adminport="19080"
changelog="1. Updated OSCam to 1.20-r11385<br>2. Added Envi template"
checksum="2724f38d447b6c5161ea818a058d6c4d"

**Comment by schumi2004** [comment]
Actually we could change title to Packages not shown for architecture 88f628x

Packages for 88f6281 are also used for 88f6282 so they share the same arch

**Comment by jdel** [comment]
I have just done some tests with curl because I don't have a 88f6282 syno anymore and I cannot reproduce the issue.

Any chance you could add my dev-repo to your syno list `https://packages-dev.fkn.ninja/` and take a screenshot of the Debug package that should be there ? The description will show some debug info.

Thanks.

**Comment by schumi2004** [comment]
Unfortunately i have sold me DS211 (88f6282) some time ago so can't test it myself either.
Just navigate to DS211 in web GUI would do the trick i think, it won't show anything unless it's noarch.
It's not a big deal for me but just something i noticed as a former 88f6282 owner ;)

**Comment by jdel** [comment]
And finally fixed by 1041de8

**Comment by schumi2004** [comment]
Confirmed and resolved, your the boss!

**Comment by jdel** [comment]
Cheers 😆
