### ISSUE TITLE
disk_free_space(): Value too large for defined data type

### ISSUE THREAD

**Issue by itn3rd77** [jdel/sspks#52]
After uploading _Simple SPK Server_ to my hoster strato.de I got the following Warning popping up.

```php
Warning: disk_free_space(): Value too large for defined data type in /mnt/web211/b3/65/54228465/htdocs/spk/lib/SSpkS/Package/Package.php on line 199 Warning: disk_free_space(): Value too large for defined data type in /mnt/web211/b3/65/54228465/htdocs/spk/lib/SSpkS/Package/Package.php on line 199 Warning: disk_free_space(): Value too large for defined data type in /mnt/web211/b3/65/54228465/htdocs/spk/lib/SSpkS/Package/Package.php on line 199 Warning: disk_free_space(): Value too large for defined data type in /mnt/web211/b3/65/54228465/htdocs/spk/lib/SSpkS/Package/Package.php on line 199 Warning: disk_free_space(): Value too large for defined data type in /mnt/web211/b3/65/54228465/htdocs/spk/lib/SSpkS/Package/Package.php on line 199 Warning: disk_free_space(): Value too large for defined data type in /mnt/web211/b3/65/54228465/htdocs/spk/lib/SSpkS/Package/Package.php on line 199 Warning: disk_free_space(): Value too large for defined data type in /mnt/web211/b3/65/54228465/htdocs/spk/lib/SSpkS/Package/Package.php on line 199 
```

This seems to be a know for problem with some hosting providers especially strato.de. Other projects also  struggled with this e.g. https://github.com/owncloud/core/issues/18886.

As there seems no reliable way to determine the free space in that case, I would suggest to ignore the error and proceed as there is no logging available (AFAIK).

I will come up with a pull request soon.

**Comment by jdel** [comment]
@itn3rd77 Until this is merged, I invite you to try out [gosspks](https://github.com/jdel/gosspks).

I completely rewrote sspks in go a couple of months ago.

Some of the benefits are:
  - Single binary to run, no dependency hell
  - No need for admin rights other than binding to a port
  - Serve packages in less than 5 minutes
  - Faster than sspks going through apache
  - Implements in-memory cache to limit IO overhead
  - On the long run, I don't plan to support sspks anymore

It has a couple of drawbacks though:
  - It is currently under development and might introduce breaking changes
  - It provides a synology api endpoint, and a public api endpoint, no UI
  - A functional UI using react/redux is in the pipes, but it's ugly for the moment

Quick start guide:

```bash
curl -sL https://bintray.com/jdel/gosspks/download_file?file_path=gosspks-linux-amd64 -o ~/gosspks-cmd
chmod +x ~/gosspks-cmd
./gosspks-cmd --packages /path/to/packages
```
