### ISSUE TITLE
Can this run on a DiskStation that can't run docker?

### ISSUE THREAD

**Issue by georgeduckett** [jdel/sspks#54]
Hi,

I'm very interested in hosting this on my Diskstation and pointing the package manager at it locally. I'd then use various scripts to place spks in the correct folder so I have a simple automated update mechanism.

As I understand it (and I'm new to PHP), the PHP code can be hosted on a DiskStation as a local web server and used to serve spks, however I see there's a docker file in here too. Is this simply a different method of hosting the web server, or is it required for the whole system to function correctly?

**Comment by mbirth** [comment]
Both works fine. You can host sspks with the Synology's web server (make sure to enable the phar extension and do everything according to the [INSTALL](https://github.com/jdel/sspks/blob/master/INSTALL.md) documentation) or use the [jdel/sspks](https://hub.docker.com/r/jdel/sspks/) Docker package.

**Comment by georgeduckett** [comment]
Great, thanks for the quick response.
