### ISSUE TITLE
HTTPS Support?

### ISSUE THREAD

**Issue by DKeppi** [jdel/sspks#56]
Hi, 

actually i host my server under http://spk.domain.tld:8080, but i want it a little bit saver.
The problem is, that **https**://spk.domain.tld:8080 does not work.
On which port the server is running for https...port 8443 is also not working inside the container.

THX for your help

BR
DKeppi

**Comment by jdel** [comment]
Hello @DKeppi,

The container is not made for handling HTTPS. The easiest way to achieve this is to offload SSL/TLS termination to a reverse proxy / load balancer. This can be achieved very easily with docker by using [traefik](https://hub.docker.com/_/traefik/), [nginx](https://hub.docker.com/_/nginx/) or [haproxy](https://hub.docker.com/_/haproxy/).

**Comment by DKeppi** [comment]
Hi @jdel 

Thanks for the fast reply, i will manage it via Synologys Reverse Proxy then :)
