### ISSUE TITLE
Domoticz v4.0.10548-8 beta on my synology armada370 notifications problem

### ISSUE THREAD

**Issue by spider7611** [jdel/sspks#58]
Always updated the beta domoticz and now have problem with the notifications. Not working at all. In the log show this: 
2019-03-18 12:03:26.935 Status: Notification: Domoticz test
2019-03-18 12:03:26.995 Error: Telegram:

**Comment by jdel** [comment]
Hello, 

This repository is only for issues related to SSPKS (the package server).

You should contact the maintainer of the package you are trying to install `Domoticz v4.0.10548-8 beta` to report the problem.

Regards,
Julien
