### ISSUE TITLE
PHP index error

### ISSUE THREAD

**Issue by echel0n** [jdel/sspks#61]
I keep getting the following error below in the logs:

`PHP Notice:  Undefined index: firmware in /var/www/localhost/htdocs/lib/SSpkS/Package/Package.php on line 79`

**Comment by jdel** [comment]
Most likely one of your packages is missing the `firmware` field in the `INFO` file.

**Comment by echel0n** [comment]
From what I can see, all my package builds are missing the `firmware` field, would you be able to share how I might go about adding that to my package please ?

**Comment by echel0n** [comment]
Doing a little digging and I actually see the use of `firmware` field in INFO files was depreciated if favor of using `os_min_ver` instead since 6.1-14715, any chance you could make a fix for this ?

Thanks!

**Comment by jdel** [comment]
Thanks for noting that. For sure I will make a fix for gosspks as cross referenced above, but sspks is not under active development anymore and there is little chance that I will backport the fix here.

I am happy to take a look at PRs though.
