### ISSUE TITLE
DSM 7.0

### ISSUE THREAD

**Issue by duduche75** [jdel/sspks#62]
Do you have an idea when the package will be compatible with new DSM 7.0

**Comment by jdel** [comment]
Hello, I can't tell that. DSM 7.0 is not even out yet and I don't have access to the Preview release.

I'm welcoming any PR that will add compatibility to `sspks`, but please bear in mind that I am not willing to maintain `sspks` anymore and will add any new features to [`gosspks`](https://github.com/jdel/gosspks) instead.

**Comment by picrap** [comment]
What we know so far is that DSM7 totally hides packages when `beta` is set to `yes` in the `INFO` file, so the fix is to simply not serve this value until they decide to address the problem.

**Comment by strausmann** [comment]
I use a NAS with DSM 7 and I try this next week.

**Comment by picrap** [comment]
Tested and approved: I was able to serve the same package version built in two flavors, for DSM 6 and 7, and it works 😎
