### ISSUE TITLE
wrong package size

### ISSUE THREAD

**Issue by c4coer** [jdel/sspks#63]
Hello
and first of all thank you for your work.
 just a little info the size of the packages is not good (19mb), i installed it and it doesn't work, i don't know if others are impacted. thank you

http://www.jadahl.com/domoticz_2020.2_python_6.2/?arch=rtd1296

**Comment by jdel** [comment]
Hello, unfortunately I am not the maintainer of those domoticz packages. Please check directly with http://www.jadahl.com/.
