### ISSUE TITLE
USB Drivers not working on DSM6.2 (RS820+)

### ISSUE THREAD

**Issue by 54Gege** [jdel/sspks#64]
Hello,
I'm trying to install USB Drivers to support RFXCOM by USB on Synology NAS Server, DSM version 6.2.3-25426 Update 2. 
The server version is RS820+.

DSM accepts to install this driver http://www.jadahl.com/drivers_6.2/?arch=denverton, but dmesg looks to report errors : 
`[ 2453.590556] usbserial: version magic '4.4.59 SMP preempt mod_unload ' should be '4.4.59+ SMP preempt mod_unload '
[ 2453.603359] ftdi_sio: Unknown symbol usb_serial_handle_sysrq_char (err 0)
[ 2453.610386] ftdi_sio: Unknown symbol usb_serial_generic_open (err 0)
[ 2453.617029] ftdi_sio: Unknown symbol usb_serial_handle_dcd_change (err 0)
[ 2453.624327] ftdi_sio: Unknown symbol usb_serial_deregister_drivers (err 0)
[ 2453.631636] ftdi_sio: Unknown symbol usb_serial_generic_unthrottle (err 0)
[ 2453.638795] ftdi_sio: Unknown symbol usb_serial_handle_break (err 0)
[ 2453.645342] ftdi_sio: Unknown symbol usb_serial_generic_get_icount (err 0)
[ 2453.652386] ftdi_sio: Unknown symbol usb_serial_generic_tiocmiwait (err 0)
[ 2453.659472] ftdi_sio: Unknown symbol usb_serial_generic_throttle (err 0)
[ 2453.666402] ftdi_sio: Unknown symbol usb_serial_register_drivers (err 0)
[ 2453.680843] cp210x: Unknown symbol usb_serial_generic_open (err 0)
[ 2453.687413] cp210x: Unknown symbol usb_serial_generic_close (err 0)
[ 2453.693941] cp210x: Unknown symbol usb_serial_deregister_drivers (err 0)
[ 2453.700967] cp210x: Unknown symbol usb_serial_register_drivers (err 0)
[ 2453.714643] pl2303: Unknown symbol usb_serial_handle_sysrq_char (err 0)
[ 2453.721465] pl2303: Unknown symbol usb_serial_generic_open (err 0)
[ 2453.728387] pl2303: Unknown symbol usb_serial_generic_close (err 0)
[ 2453.734864] pl2303: Unknown symbol usb_serial_handle_dcd_change (err 0)
[ 2453.742010] pl2303: Unknown symbol usb_serial_deregister_drivers (err 0)
[ 2453.748897] pl2303: Unknown symbol usb_serial_handle_break (err 0)
[ 2453.755582] pl2303: Unknown symbol usb_serial_generic_tiocmiwait (err 0)
[ 2453.762441] pl2303: Unknown symbol usb_serial_register_drivers (err 0)
[ 2453.775766] ch341: Unknown symbol usb_serial_generic_open (err 0)
[ 2453.782219] ch341: Unknown symbol usb_serial_generic_close (err 0)
[ 2453.788625] ch341: Unknown symbol usb_serial_handle_dcd_change (err 0)
[ 2453.795348] ch341: Unknown symbol usb_serial_generic_resume (err 0)
[ 2453.801968] ch341: Unknown symbol usb_serial_deregister_drivers (err 0)
[ 2453.808834] ch341: Unknown symbol usb_serial_generic_tiocmiwait (err 0)
[ 2453.815894] ch341: Unknown symbol usb_serial_register_drivers (err 0)
[ 2453.827709] ti_usb_3410_5052: Unknown symbol usb_serial_deregister_drivers (err 0)
[ 2453.835490] ti_usb_3410_5052: Unknown symbol usb_serial_generic_get_icount (err 0)
[ 2453.843996] ti_usb_3410_5052: Unknown symbol usb_serial_generic_tiocmiwait (err 0)
[ 2453.852243] ti_usb_3410_5052: Unknown symbol usb_serial_register_drivers (err 0)
`
And, RFXCom is not working properly. lsusb detects the usb device : 
`Bus 001 Device 008: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC
`
The connection is visible in dmesg : 
`[ 2502.626166] usb 1-3.4: new full-speed USB device number 8 using xhci_hcd
`
But no ttyACMx or ttyUSB is created.

Could it be an issue due to new DSM version ?
Thanks.

**Comment by 54Gege** [comment]
I just found something similar here : https://github.com/jdel/sspks/issues/59
This happends after installing the drivers, and then at every start of the server too.

**Comment by 54Gege** [comment]
Just in case of, I found the file that is concerned by the error : 
`usbserial: version magic '4.4.59 SMP preempt mod_unload ' should be '4.4.59+ SMP preempt mod_unload`
It's located into `UsbSerialDrivers_denverton-6.2_6-4.spk/package.tgz/package.tar/modules/usbserial.ko` where the "+" looks to be missing.
Is that right ?

**Comment by jdel** [comment]
Hello, 

This repository is only for issues related to SSPKS (the package server).

You should contact the maintainer of the package you are trying to install `USB Serial Drivers ` to report the problem.

Regards,
Julien
