### ISSUE TITLE
Compatibility with Ryzen-based devices, such as the DS1621+ or DS1821+

### ISSUE THREAD

**Issue by mg0716** [jdel/sspks#65]
I was researching your project and was interested in using the USB drivers, but noticed that none of the Ryzen-based devices are listed as supported explicitly. As it's unclear to me whether or not I'd be able to select another model to attempt an install, I thought before venturing down that path I'd raise this issue.

If there's another way to take, or a model that I could select to install it—great—otherwise I thought it would be worthwhile to bring up the possibility of adding these models!

Thanks

**Comment by jdel** [comment]
Hello,

This repository is only for issues related to SSPKS (the package server).

You should contact the maintainer of the package you are trying to install to report the problem.
Maybe people who raised #64 or #59 have an answer for you.

Regards,
Julien
