### ISSUE TITLE
Update with all new models - Stand 05/2021

### ISSUE THREAD

**Issue by strausmann** [jdel/sspks#71]
Update with the current models from 05/2021

**Comment by jdel** [comment]
Thanks for your submissions. I will try to take a look this week.

**Comment by strausmann** [comment]
Any Updates?

**Comment by strausmann** [comment]
Good Day, please Review and merge my PR. Thx

**Comment by strausmann** [comment]
#72

**Comment by picrap** [comment]
Hi, I will do this in the very next few days. Sorry for delay and thanks for patience.

**Comment by picrap** [comment]
Done!
