### ISSUE TITLE
Invalid location with DSM 5.1-4977

### ISSUE THREAD

**Issue by cybfr** [jdel/sspks#8]
Thank you for this great package wich save me lot of reverse engineering time...

By the way with DSM 5.1-4977 the DSM does not accept my repo, invesigating a bit I saw tha DSM makes first a GET request with
<code>
ds_sn=C7L1Nxxxxxx&unique=synology_qoriq_213%2B&language=fre&package_update_channel=beta&major=5&arch=qoriq&build=4977&timezone=Brussels&minor=1 
</code>
and expect a json list of packages and then a POST with same data and still expecting a json list...

The following patch fix this :

diff --git a/index.php b/index.php
index d18ca4b..d5d0c4d 100644
--- a/index.php
+++ b/index.php
@@ -22,16 +22,16 @@ $host = $_SERVER['HTTP_HOST'].substr($_SERVER['REQUEST_URI'], 0, strrpos($_SERVE

 $siteName = "Simple SPK Server";

-if($_SERVER['REQUEST_METHOD'] == 'POST'){
+if(isset($_REQUEST['ds_sn'])){
-    $language = trim($_POST['language']);
-    $timezone = trim($_POST['timezone']);
-    $arch = trim($_POST['arch']);
-    $major = trim($_POST['major']);
-    $minor = trim($_POST['minor']);
-    $build = trim($_POST['build']);
-    $channel = trim($_POST['package_update_channel']);
-    $unique = trim($_POST['unique']);
-    $language = trim($_REQUEST['language']);
-    $timezone = trim($_REQUEST['timezone']);
-    $arch = trim($_REQUEST['arch']);
-    $major = trim($_REQUEST['major']);
-    $minor = trim($_REQUEST['minor']);
-    $build = trim($_REQUEST['build']);
-    $channel = trim($_REQUEST['package_update_channel']);
-    $unique = trim($_REQUEST['unique']);
  
   if (!$language || !$timezone || !$arch || !$major || is_null($minor) || !$build || !$channel || !$unique || !$serial || !(preg_match("/^$unique/", $_SERVER['HTTP_USER_AGENT']) || $_SERVER['HTTP_USER_AGENT'] == "\"Mozilla/4.0 (compatible; MSIE 6.1; Windows XP) Synology\"" || $_SERVER['HTTP_USER_AGENT'] == "\"Mozilla/4.0 (compatible; MSIE 6.1; Windows XP)\"" )){
       header('Content-type: text/html');
  </code>

That said, there still a pb with the test on $serial, I needed to squeeze it (don't know where and how it's supposed to be initalized but is not...

Thanks & cheers

**Comment by Martijn085** [comment]
Any update on this? What i can see is that this is going wrong with the DS411+II with DSM 5.x if this one is running 4.x there is no problem.

**Comment by jdel** [comment]
Hi, sorry I never had any time to have a look at this issue just yet.
I will try to do it over the week.

**Comment by Martijn085** [comment]
Would be great, thanks!

**Comment by Martijn085** [comment]
@jdel do you have any update on this?

**Comment by colin1497** [comment]
I had the same issue, DSM 5.1-5022 Update 5.  Removing the Serial test allowed it to work.  Haven't pursued further...

**Comment by mbirth** [comment]
No worky in DSM 5.2-5592 Update 3. Can't add it as a package source due to `Invalid location.` error.

**Comment by bipsendk** [comment]
Found a way to get it working with 5.2-5592 update 2 ... My version now supports GPG key entry as well...
Let me know if I should submit a diff file...

**Comment by jdel** [comment]
Sorry, never had time to look into the issue. @bipsendk, a pull request in github would be much appreciated.

**Comment by bipsendk** [comment]
@jdel - I tried to fork and do a pull request to edit index.php ... I don't know if I did it correct, as I'm not so familiar with the use of git...

Let me know whether you can see my changes or not....

**Comment by bipsendk** [comment]
I am still having an issue with my icon not being displayed correctly in package manager under "Community" where 3rd party packages are listed... I am still investigating on this issue..

**Comment by mbirth** [comment]
Any news here or can this be closed?

**Comment by jdel** [comment]
I think this can be closed, the initial patch proposed is impossible to apply. 

Please use the latest version of SSPKS and reopen an issue if the problem persists.
