### ISSUE TITLE
Create a new Release and Update the latest tag

### ISSUE THREAD

**Issue by strausmann** [jdel/sspks#80]
Good Day,
Can you create a new Release and updating the latest tag docker images and publish it in the decker hub? 

Thanks
Bjoern

**Comment by picrap** [comment]
I am confused by the current `CHANGELOG.md`. Versions are unordered, so I am going to merge all of these in a 1.1.6 and make a release with. However, I have no idea on how to release this on docker; this is something we should automate.

**Comment by jdel** [comment]
Docker hub images are already automated. Every branch/pr you push is also built for easy testing

**Comment by strausmann** [comment]
we should urgently automate this. The latest tag should always be linked to each new release. The latest tag is now 3 years old. Which is difficult to understand, for example, when downloading the Docker image on a Synology NAS. Why the latest tag is 3 years old.

**Comment by strausmann** [comment]
@jdel This is true, but unfortunately the latest tag is not changed to the last release tag.

**Comment by picrap** [comment]
Done! https://github.com/jdel/sspks/releases/tag/v1.1.6

**Comment by picrap** [comment]
@strausmann if it’s OK for you, feel free to close the issue.

**Comment by jdel** [comment]
I have updated the tag `latest` in docker hub too. The original idea was that I would only override the `latest` tag once I pulled and tested manually the last `vx.y.z` tag.

As I've not been good at doing this, we will see at automating that for next release.

**Comment by strausmann** [comment]
Thank you very much
