### ISSUE TITLE
Packages available for DSM6 are also listed for DSM7

### ISSUE THREAD

**Issue by picrap** [jdel/sspks#82]
The filters does the job correctly (DSM does not): if a package is available for a 6.x version it will be listed when requested by a DSM 7.
The filter has to be split in two: a pre-7 and post-7 filter

**Comment by jdel** [comment]
Did Syno break backwards compatibility ? It seems normal to me that DSM7 can install DSM6 packages (unless they broke compat).

sspks is supposed to return the highest version of the package available for the DSM version requesting it. 

This could be related to https://github.com/jdel/gosspks/issues/11 and the fact we still use the `firmware` field ?

**Comment by picrap** [comment]
No, DSM7 won’t install packages with os_min_version below 7.0 because they broke the compatibility (no more root packages allowed, no GPG signature required and icons size have changed, at least. Only the first change is blocking but that’s enough).
It is unrelated to jdel/gosspks#11.
