### ISSUE TITLE
Docker image (latest) does not work

### ISSUE THREAD

**Issue by MartinRothschink** [jdel/sspks#86]
**Docker image says:**
Autoloader not found! Did you follow the instructions from the INSTALL.md?
(If you want to keep the old version, switch to the legacy branch by running: git checkout legacy

I tracked the install and the issue is here:

> /home/user # curl -sSL https://getcomposer.org/download/1.6.5/composer.phar -o /usr/local/bin/composer
> /home/user # chmod +x /usr/local/bin/composer
> /home/user # cd /var/www/localhost/htdocs
> /var/www/localhost/htdocs # composer install --no-dev
> 
> PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php:661
> Stack trace:
> #0 phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/bootstrap.php(48): Symfony\Polyfill\Mbstring\Mbstring::mb_strwidth('  [Composer\\Exc...', 'ASCII')
> #1 phar:///usr/local/bin/composer/vendor/symfony/console/Helper/Helper.php(54): mb_strwidth('  [Composer\\Exc...', 'ASCII')
> #2 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(654): Symfony\Component\Console\Helper\Helper::strlen('  [Composer\\Exc...')
> #3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(127): Symfony\Component\Console\Application->renderException(Object(Composer\Exception\NoSslException), Object(Symfony\Component\Console\Output\StreamOutput))
> #4 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(100): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object( in phar:///usr/local/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 661

**Comment by picrap** [comment]
I am totally incomptetent for this. It look like a job for @jdel 😉

**Comment by 3x3cut0r** [comment]
The Dockerfile should be updated to new alpine and composer versions! 
composer 2.2.6 instead of 1.6.5 should fix this issue.
btw we can update alpine to 3.14 too.

**Comment by picrap** [comment]
Hi, could you provide a pull request?

**Comment by 3x3cut0r** [comment]
its on https://github.com/3x3cut0r/docker/blob/main/sspks/Dockerfile
or what do you meen?

**Comment by 3x3cut0r** [comment]
related to my other problem [#68](https://github.com/jdel/sspks/issues/68)
i use my image with env:
COMPOSER_HOME="/cache"
to fix the permission errors

**Comment by picrap** [comment]
The only significant change I see in your Dockerfile is the change in composer version, am I right?
If yes, I can update the Dockerfile here.

**Comment by 3x3cut0r** [comment]
yes and the base image which provides a newer alpine image and a correctly installed composer 2.2.6 environment with php-8.
your image installes php7 ... maybe we could also update to 8?!

**Comment by picrap** [comment]
I made the two changes in the Dockerfile, let me know if it works
(PHP 8 is another story 😅)

**Comment by 3x3cut0r** [comment]
did you update your docker image on dockerhub too?
its still the old one ...

**Comment by picrap** [comment]
I am no Docker user at all, but the original author @jdel told me the deployment is automated.

**Comment by jdel** [comment]
looks like the CI responsible for building doesn't work anymore, i'll have to look into it

**Comment by jdel** [comment]
Turns out I needed to migrate the repo to the new travis CI. The docker build still has an error https://app.travis-ci.com/github/jdel/sspks/builds/246543710

**Comment by picrap** [comment]
The `mkdir /run/apache` was removed from @3x3cut0r `Dockerfile`, perhaps a `mkdir -p …` could do the trick.

**Comment by picrap** [comment]
It did 😎 https://app.travis-ci.com/github/jdel/sspks/builds/246544203

**Comment by jdel** [comment]
Looks like docker hub has put automated builds behing a paywall now. I'll have to look into replacing docker repository and possibly travis ci to github actions and github packages.

**Comment by 3x3cut0r** [comment]
scheduled actions to dockerhub is not working anymore ... but you can still run git actions on push to docker hub. see my git action for sspks which push the Dockerfile to docker hub on every push:
https://github.com/3x3cut0r/docker/blob/main/.github/workflows/sspks.yml

**Comment by jdel** [comment]
Yes I need to migrate to github actions at some point but I don't have much time right now. I did a few changes in the Dockerfile and pushed a new docker image `jdel/sspks:updated-dockerfile` if someone wants to try and let me know.

**Comment by 3x3cut0r** [comment]
although I can't find now any differences between your dockerfile and mine ... jdel/sspks:updated-dockerfile still gets me "Autoloader not found!" error message while mine does not ...

**Comment by jdel** [comment]
My bad, I pushed the wrong one, can you give it another go ?
It was missing some new php8 dependencies. Should be good now.

**Comment by 3x3cut0r** [comment]
now its running!

**Comment by jdel** [comment]
Workflows are now fixed. `latest` corresponds to the latest release (now v1.2.0), while `master` is the edge package with unreleased changes.
